{{- if .Values.secrets.jwtSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assistant-api.fullname" . }}-secrets
type: Opaque
stringData:
  jwtSecretKey: {{ .Values.secrets.jwtSecretKey | quote }}
{{- end }}
